//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisorMapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosMapa
    {
        public int IdMapa { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
        public Nullable<short> Radio { get; set; }
        public string Direccion { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geographic { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
